Repository wrtnio/openai-function-schema, pull requests merged in 2024-07, with the labels that each got.

#3 Add more documentation comments
  src/structures/IOpenAiSchema.ts
  src/structures/ISwaggerMigrate.ts
  src/structures/ISwaggerMigrateRoute.ts
  src/structures/ISwaggerOperation.ts
  src/structures/ISwaggerPath.ts
  src/structures/ISwaggerSchema.ts
Labels: documentation, enhancement

#4 New option `IOpenAiDocument.IOptions.separate`.
  README.md
  package.json
  src/OpenAiComposer.ts
  src/OpenAiFetcher.ts
  src/OpenAiTypeChecker.ts
  src/internal/OpenAiSchemaSeparator.ts
  src/structures/IOpenAiDocument.ts
  src/structures/IOpenAiFunction.ts
  test/features/composer/test_composer_keyword.ts
  test/features/composer/test_composer_positional.ts
  test/features/composer/test_composer_schema.ts
  test/features/fetcher/keyword/test_fetcher_keyword_bbs_article_abridges.ts
  test/features/fetcher/keyword/test_fetcher_keyword_bbs_article_at.ts
  test/features/fetcher/keyword/test_fetcher_keyword_bbs_article_create.ts
  test/features/fetcher/keyword/test_fetcher_keyword_bbs_article_index.ts
  test/features/fetcher/keyword/test_fetcher_keyword_bbs_article_update.ts
  test/features/fetcher/keyword/test_fetcher_keyword_multipart_post.ts
  test/features/fetcher/keyword/test_fetcher_keyword_query_body.ts
  test/features/fetcher/keyword/test_fetcher_keyword_query_composite.ts
  test/features/fetcher/keyword/test_fetcher_keyword_query_individual.ts
  test/features/fetcher/keyword/test_fetcher_keyword_query_nest.ts
  test/features/fetcher/keyword/test_fetcher_keyword_query_typed.ts
  test/features/fetcher/positional/test_fetcher_positional_bbs_article_abridges.ts
  test/features/fetcher/positional/test_fetcher_positional_bbs_article_at.ts
  test/features/fetcher/positional/test_fetcher_positional_bbs_article_create.ts
  test/features/fetcher/positional/test_fetcher_positional_bbs_article_index.ts
  test/features/fetcher/positional/test_fetcher_positional_bbs_article_update.ts
  test/features/fetcher/positional/test_fetcher_positional_multipart_post.ts
  test/features/fetcher/positional/test_fetcher_positional_query_body.ts
  test/features/fetcher/positional/test_fetcher_positional_query_composite.ts
  test/features/fetcher/positional/test_fetcher_positional_query_individual.ts
  test/features/fetcher/positional/test_fetcher_positional_query_nest.ts
  test/features/fetcher/positional/test_fetcher_positional_query_typed.ts
  test/features/separate/test_schema_separate_array.ts
  test/features/separate/test_schema_separate_nested.ts
  test/features/separate/test_schema_separate_object.ts
  test/features/separate/test_schema_separate_string.ts
  test/index.ts
  test/structures/ITestProps.ts
Labels: enhancement

#5 Completion of `OpenAiDataCombiner`
  README.md
  package.json
  src/OpenAiComposer.ts
  src/OpenAiDataCombiner.ts
  src/OpenAiFetcher.ts
  src/internal/OpenAiSchemaSeparator.ts
  src/module.ts
  test/api/structures/IMembership.ts
  test/controllers/MembershipController.ts
  test/controllers/TestModule.ts
  test/features/combiner/test_combiner_keyword_parameters_body.ts
  test/features/combiner/test_combiner_keyword_parameters_path.ts
  test/features/combiner/test_combiner_keyword_parameters_query.ts
  test/features/combiner/test_combiner_positional_parameters_body.ts
  test/features/combiner/test_combiner_positional_parameters_path.ts
  test/features/combiner/test_combiner_positional_parameters_query.ts
  test/features/combiner/test_combiner_value.ts
  test/features/composer/test_composer_schema.ts
  test/features/separate/test_schema_separate_array.ts
  test/features/separate/test_schema_separate_nested.ts
  test/features/separate/test_schema_separate_object.ts
  test/index.ts
  test/keyword.json
  test/positional.json
  test/structures/ITestProps.ts
  test/swagger.json
  tsconfig.json
Labels: documentation, enhancement

#6 CLI + README enhancement
  .github/workflows/build.yml
  README.md
  package.json
  src/OpenAiComposer.ts
  src/executable/internal/ArgumentParser.ts
  src/executable/wofs.ts
  src/index.ts
  test/plain.json
  tsconfig.json
Labels: documentation, enhancement

#7 Deploy configuration
  deploy/index.ts
  package.json
  packages/alias/.gitignore
Labels: enhancement

#9 Add example files
  deploy/examples.ts
  examples/keyword/bbs.json
  examples/keyword/clickhouse.json
  examples/keyword/fireblocks.json
  examples/keyword/iamport.json
  examples/keyword/petstore.json
  examples/keyword/shopping.json
  examples/keyword/toss.json
  examples/keyword/uber.json
  examples/positional/bbs.json
  examples/positional/clickhouse.json
  examples/positional/fireblocks.json
  examples/positional/iamport.json
  examples/positional/petstore.json
  examples/positional/shopping.json
  examples/positional/toss.json
  examples/positional/uber.json
  examples/swagger/bbs.json
  examples/swagger/clickhouse.json
  examples/swagger/fireblocks.json
  examples/swagger/iamport.json
  examples/swagger/petstore.json
  examples/swagger/shopping.json
  examples/swagger/toss.json
  examples/swagger/uber.json
  package.json
Labels: documentation, enhancement

#10 docs: update README.md
  README.md
Labels: documentation, good first issue

#11 Fix: export omitted ISwaggerSchema
  package.json
  src/module.ts
Labels: bug

#12 Fix `ISwaggerSchema.IOneOf` type.
  package.json
  src/structures/ISwaggerSchema.ts
Labels: bug, enhancement

#13 Remove `oneOf.discriminator` property.
  package.json
  src/OpenAiComposer.ts
  test/features/composer/test_composer_schema_oneof.ts
Labels: enhancement

#14 Bump up `@nestia/e2e` dependency.
  package.json
  test/index.ts
Labels: enhancement

#15 Break change from `@samchon/openapi`.
  .github/dependabot.yml
  package.json
  src/OpenAiComposer.ts
  test/features/composer/test_composer_schema.ts
Labels: enhancement

#16 Change examples
  examples/keyword/bbs.json
  examples/keyword/clickhouse.json
  examples/keyword/fireblocks.json
  examples/keyword/iamport.json
  examples/keyword/petstore.json
  examples/keyword/shopping.json
  examples/keyword/toss.json
  examples/keyword/uber.json
  examples/positional/bbs.json
  examples/positional/clickhouse.json
  examples/positional/fireblocks.json
  examples/positional/iamport.json
  examples/positional/petstore.json
  examples/positional/shopping.json
  examples/positional/toss.json
  examples/positional/uber.json
  examples/swagger/bbs.json
  examples/swagger/iamport.json
  examples/swagger/shopping.json
  examples/swagger/toss.json
  test/example.ts
Labels: documentation, enhancement

#17 Add `OpenAiFetcher.propagate()` function.
  package.json
  src/OpenAiFetcher.ts
Labels: enhancement

#19 fix: allow union type of prerequisite
  src/structures/IOpenAiSchema.ts
  src/structures/ISwaggerSchema.ts
Labels: bug, enhancement
